### ISSUE TITLE
Nonfunctioning es_is and e_is classes

### ISSUE THREAD

**Issue by michaelraheb** [neelsmith/tabulae#79]
Regarding the es_is and e_is classes not functioning:

1.) Background
-I added rules for the es_is and e_is classes, the respective genders being feminine and neuter.
-I added the stem "nub" for nubes and "sedil" for "sedile" - nubes being feminine, sedile being neuter.
-The parser did not recognize my testforms for nubes and sedile. 

2.) Fixes
-The parser compiled as normal but still did not recognize the forms.
-I checked the rules against other, already-working rules, and there are no significant differences.
-I cross-checked the genders of the stems and the rules.
-I parsed wordlists and analyzed with fst-mor. Neither solved the problem.
-I rewrote the es_is file to make sure there wasn't anything "hiding" in the text.
-I deleted and re-added the es_is stem.
-Other es_is stems have not parsed in my testforms for the chapters of Pliny.
-There are no copies of the classes in the "fst/symbols" file.

**Comment by neelsmith** [comment]
Closing
